spring:
  application:
    name: document-processor-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ats_optimizer}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8081}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:ats-optimizer-documents}
    region: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}

logging:
  level:
    com.atsoptimizer: INFO
    org.springframework.web: INFO