spring:
  application:
    name: job-analyzer-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ats_optimizer}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

server:
  port: ${PORT:8082}

# Upstash Redis REST API (for cloud deployment)
upstash:
  redis:
    url: ${UPSTASH_REDIS_REST_URL:}
    token: ${UPSTASH_REDIS_REST_TOKEN:}

cache:
  ttl: 3600  # 1 hour in seconds

logging:
  level:
    com.atsoptimizer: INFO
    org.springframework.web: INFO