spring:
  application:
    name: ai-orchestrator-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ats_optimizer}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8083}

# Service URLs
services:
  document-processor:
    url: ${DOCUMENT_SERVICE_URL:http://localhost:8081}
  job-analyzer:
    url: ${JOB_SERVICE_URL:http://localhost:8082}

# LLM Configuration
llm:
  provider: ${LLM_PROVIDER:anthropic}  # anthropic or openai
  anthropic:
    api-key: ${ANTHROPIC_API_KEY:}
    model: ${ANTHROPIC_MODEL:claude-sonnet-4-20250514}
    api-url: https://api.anthropic.com/v1/messages
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: ${OPENAI_MODEL:gpt-4}
    api-url: https://api.openai.com/v1/chat/completions

# Agent Configuration
agents:
  keyword-matcher:
    weight: 0.30  # 30% of total score
  ats-checker:
    weight: 0.25  # 25% of total score
  content-quality:
    weight: 0.25  # 25% of total score
  llm-analysis:
    weight: 0.20  # 20% of total score

logging:
  level:
    com.atsoptimizer: INFO